// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvmZxeQn9Slki83srC3Fk-BT9tkI3yqDI',
    appId: '1:874114819410:android:9b9a32d8214d96ec24468b',
    messagingSenderId: '874114819410',
    projectId: 'travel-app-93f39',
    storageBucket: 'travel-app-93f39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFW3KLQQUJIaNznXQ-6mhcIASRlZHOTMw',
    appId: '1:874114819410:ios:fd7e972fd704b1c124468b',
    messagingSenderId: '874114819410',
    projectId: 'travel-app-93f39',
    storageBucket: 'travel-app-93f39.firebasestorage.app',
    androidClientId:
        '874114819410-01qabi4d1fu5bsoec68i2hi0gaqjg5cc.apps.googleusercontent.com',
    iosClientId:
        '874114819410-s7r5cspv61pvkpknoe4agvuqm8u2811e.apps.googleusercontent.com',
    iosBundleId: 'com.royaldusk.app.ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFW3KLQQUJIaNznXQ-6mhcIASRlZHOTMw',
    appId: '1:874114819410:ios:6502ae69f69e085924468b',
    messagingSenderId: '874114819410',
    projectId: 'travel-app-93f39',
    storageBucket: 'travel-app-93f39.firebasestorage.app',
    iosClientId:
        '874114819410-md66ouov3e0ifbqvstjrnfbs2p0hn7ll.apps.googleusercontent.com',
    iosBundleId: 'com.example.royalduskMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzjRDDjSpuRskcyGc76q2DehMCX4lyUjI',
    appId: '1:874114819410:web:77bd41186c70d4c524468b',
    messagingSenderId: '874114819410',
    projectId: 'travel-app-93f39',
    authDomain: 'travel-app-93f39.firebaseapp.com',
    storageBucket: 'travel-app-93f39.firebasestorage.app',
    measurementId: 'G-QY1QJRHQVY',
  );
}
